### ISSUE TITLE
lack EgoGoal.h 

### ISSUE THREAD

**Issue by tcjcxy30** [MattDerry/model_predictive_navigation#1]
hello MattDerry:
        I want to use mpc controllor in ros and I find you awesome work.
        The EgoGoal.h file is lack in the include folder, how can I find this file, can you help me?
        Thank you very much.

**Comment by MattDerry** [comment]
So EgoGoal is a message type, which means that catkin_make should autogenerate the EgoGoal.h file when you build the project.  You can find the definition of the EgoGoal message in the /msg folder.

**Comment by WangJIankun1992** [comment]
@CxyCH Your mpc controller can work ?
